name: Conventional Commit Checker

on:
  push:
    branches: [ develop, staging, stable ]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-commitlint-${{ hashFiles('**/commitlint.config.js') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-node--commitlint-

      - name: Install Node.js dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Commitlint dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --save-dev @commitlint/cli @commitlint/config-conventional

      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint $(echo $(git log -1 --pretty=%s) > temp.txt) -e temp.txt

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint $(echo $(git log -1 --pretty=%s) > temp.txt) -e temp.txt --verbose
