name: Run Python script

on:
  pull_request:
    types: [closed] 
    branches:
      - stable

jobs:
  build:
    if: github.event.pull_request.merged == true 
        && github.event.pull_request.state == 'closed'
        && github.event.pull_request.base.ref == 'stable'
        && github.event.pull_request.head.ref == 'release-please--branches--stable--components--release-please-action'  
    runs-on: ubuntu-latest

    steps:
    - name: Wait 
      run: sleep 45
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Download script
      run: |
        mkdir scripts
        cd scripts
        wget https://raw.githubusercontent.com/Devamparikh/Jira-release-script/development/jira_release_automation.py
    - name: Run script
      run: python scripts/jira_release_automation.py 
      env:
        JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
