name: Run Python script

on:
  pull_request:
    types: [closed] 
    branches:
      - develop
 
jobs: 
  build:
    if: github.event.pull_request.merged == true 
            && github.event.pull_request.state == 'closed'
            && github.event.pull_request.base.ref == 'stable'
            && github.event.pull_request.head.ref == 'release-please--branches--stable--components--release-please-action'  
    runs-on: ubuntu-latest

    steps:
    - name: Wait for Release please to succeed
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
          ref: ${{ github.ref }}
          check-name: 'release-please'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 40
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git
    - name: Download script
      run: |
        mkdir scripts
        cd scripts
        wget https://raw.githubusercontent.com/Devamparikh/Jira-release-script/development/requirements.txt
        wget https://raw.githubusercontent.com/Devamparikh/Jira-release-script/development/jira_release_automation.py
    - name: Install dependencies
      run: pip install -r scripts/requirements.txt
    - name: Run script
      run: python scripts/jira_release_automation.py 
      env:
        JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        RELEASE_NAME_PREFIX: 'Seller'  
