name: Extract Jira IDs from commit

on:
  push:
    branches:
      - develop

jobs:
  extract-jira-ids:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get latest release tag
      id: get_latest_tag
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data } = await github.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          console.log(data.tag_name);
          return data.tag_name;
    - name: Extract Jira IDs
      if: ${{ always() }}
      run: |
        commit_msg=$(git log -1 --pretty=%B)
        jira_ids=$(echo "$commit_msg" | grep -Eo '[A-Z]{2,}-[0-9]+' | paste -sd ",")
        echo "::set-output name=jira_ids::$jira_ids"
    - name: Create Jira Release
      run: |
          curl --request POST \
           --url 'https://devamparikh.atlassian.net/rest/api/3/version' \
           --user 'devamparikh15@gmail.com:ATATT3xFfGF01fRCVBx861BCAxTztQULOtZbXn7zdExyuKy2N51kCargm8jVI7o06a3-Fr9hxETAhcvL18pSMxzRgj5Ao9XRf1ROPOfPDlkFyD-4RXKTLkTcXeMxVdgJJcruysFV_JlCBwhZVhwkM5J9x7BbZpLlPjIx_li7EL1cS2hOJ_7PQWw=27768DD0' \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --data '{
            "name": ${{ steps.get_latest_tag.outputs.result }},
            "projectId": 10000,
            "description": "An Automated created release",
            "released": false,
            "releaseDate": null,
            "archived": false,
            "startDate": null
          }'
