name: Release and Jira Automation

on:
  push:
    branches:
      - stable

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Set release date
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          pull-request-header: "Release created at ${{ env.RELEASE_DATE }}"
          default-branch: stable

  jira-automation:
    needs: release-please
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/stable'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Checkout script repository
        uses: actions/checkout@v2
        with:
          repository: Devamparikh/Jira-release-script
          ref: development
      - name: Run script
        run: python Jira-release-script/jira_release_automation.py 
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
