name: test

on:
  push:
    branches:
      - develop

jobs:
  git-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Working Directory
        run: pwd

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Install awk
        run: sudo apt-get update && sudo apt-get install -y gawk

      - name: Print Git Log
        run: git log --pretty=%B

      - name: Filter Git Log with awk
        run: git log --pretty=%B | awk "/release-please--branches--stable--components--release-please-action/{print}"

      - name: Filter and Write to Output File
        run: git log --pretty=%B | awk "/release-please--branches--stable--components--release-please-action/{c++;if(c==2)exit} c==1" > output.txt

      - name: Print Output File
        run: cat output.txt
