name: test

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print working directory
      run: pwd
    - name: Print git log
      run: git log --pretty=%B
    - name: Print awk output
      run: git log --pretty=%B | awk "/release-please--branches--stable--components--release-please-action/{print}"
    - name: Print output file
      run: cat output.txt
